baseURL = "https://redzhift.github.io/"
locale = "en-us"
title = "Jin"
avatar = "/static/avatar.jpg"
theme = ["hugo-embed-pdf-shortcode", "m10c"]
enableInlineShortcodes = true

[pagination]
    pagerSize = 4

[menu]
    [[menu.main]]
        identifier = "home"
        name = "Home"
        url = "/"
        weight = 1
    [[menu.main]]
        identifier = "docs"
        name = "Docs"
        url = "/docs/"
        weight = 2
    [[menu.main]]
        identifier = "articles"
        name = "Articles"
        url = "/articles/"
        weight = 3
    [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 4
[params]
    author = "Jin"
    description = "Technical Writer, he/him"
    menu_item_separator = " / "
    [[params.social]]
        icon = "brand-linkedin"
        name = "LinkedIn"
        url = "https://linkedin.com/in/redzhift"
    [[params.social]]
        icon = "brand-confluence"
        name = "Confluence"
        url = "https://redzhift.atlassian.net/wiki/spaces/~jcho/overview"
    [[params.social]]
        icon = "brand-github"
        name = "GitHub"
        url = "https://github.com/redzhift"
    [params.style]
        darkestColor = "#242933"
        darkColor = "#2e3440"
        lightColor = "#e0e2ea"
        lightestColor = "#9eafc9"
        primaryColor = "#818eab"


[caches]
    [[caches.images]]
        dir = ":cacheDir/images"
    [[caches.pdfs]]
        dir = ":cacheDir/pdfs"